Get the ALB output and ECR URLs

diff --git a/.github/workflows/dev-pipeline.yml b/.github/workflows/dev-pipeline.yml
--- a/.github/workflows/dev-pipeline.yml
+++ b/.github/workflows/dev-pipeline.yml
@@ -37,9 +37,21 @@ jobs:
 
           echo "Initializing Terraform..."
 
-      # - name: Get ALB DNS Output
-      #   id: alb
-      #   working-directory: ./Terraform/terraform/Environments/Development
-      #   run: |
-      #     ALB_URL=$(terraform output -raw alb_dns_name)
-      #     echo "ALB_URL=$ALB_URL" >> $GITHUB_ENV
+      - name: Get ALB DNS Output
+        id: alb
+        working-directory: ./Terraform/terraform/Environments/Development
+        run: |
+          ALB_URL=$(terraform output -raw alb_dns_name)
+          echo "ALB_URL=$ALB_URL" >> $GITHUB_ENV
+
+      - name: Get ECR URLs
+        id: ecr
+        working-directory: ./Terraform/terraform/Environments/Development
+        run: |
+          FLASK_ECR_URL=$(terraform output -raw flask_repo_url) || { echo "Failed to get flask_repo_url"; exit 1; }
+          echo "FLASK_ECR_URL is: $FLASK_ECR_URL"
+          echo "FLASK_ECR_URL=$FLASK_ECR_URL" >> $GITHUB_ENV
+
+          NEXTJS_ECR_URL=$(terraform output -raw nextjs_repo_url) || { echo "Failed to get nextjs_repo_url"; exit 1; }
+          echo "NEXTJS_ECR_URL is: $NEXTJS_ECR_URL"
+          echo "NEXTJS_ECR_URL=$NEXTJS_ECR_URL" >> $GITHUB_ENV
